### ISSUE TITLE
<Greenlet at 0xa1183ec: main> failed with DistributionNotFound

### ISSUE THREAD

**Issue by bbigras** [abourget/pyramid_socketio#3]
I got a `DistributionNotFound` error. Any idea?

```
$ sudo socketio-serve-reload development.ini
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.6/dist-packages/pyramid_socketio/serve.py", line 48, in main
    app = loadapp('config:%s' % cfgfile, relative_to='.')
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/usr/local/lib/python2.6/dist-packages/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: test-pyramid-socketio
<Greenlet at 0x958e3ec: main> failed with DistributionNotFound

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.6/dist-packages/pyramid_socketio/serve.py", line 60, in reloader
    from paste import reloader
ImportError: cannot import name reloader
<Greenlet at 0x958ef2c: reloader> failed with ImportError
```

Here's how I created the project :

```
virtualenv --no-site-packages env
cd env
source bin/activate
pip install pyramid_socketio
bin/pcreate -s alchemy test-pyramid-socketio

cd test-pyramid-socketio

../bin/python setup.py develop
../bin/python setup.py test -q
../bin/populate_test-pyramid-socketio development.ini

../bin/pserve development.ini
```

**Comment by abourget** [comment]
Hi,

This error message occurs when you try to use the reload mechanism that is
borrowed from one of the paste\* packages. Pyramid 1.3 removed paste\* as
dependencies and so they are missing for pyramid_socketio.

You might be able to run the socketio-serve program without paste,
otherwise,  simply install them and see what it says.

Btw,  I didn't test myself with pyramid 1.2, so any patch or input is
appreciated.  Work is underway to support socket.io 0.7+

The package is either paste,  pastescript or pastedeploy. I can't check
right now.

Alexandre
Le 6 fvr. 2012 11:59, "Bruno Bigras" <
reply@reply.github.com>
a crit :

**Comment by sontek** [comment]
I can confirm that the issue that causes this is missing pastescript.  You might want to make it a dependency if the script is going to depend on it.  Or at least have it do an import check to give an intelligent error.

**Comment by abourget** [comment]
Yes, indeed :P
